---
# Example: S3 Bucket Claim for Development
apiVersion: platform.example.com/v1alpha1
kind: Bucket
metadata:
  name: dev-app-storage
  namespace: dev
  labels:
    app: my-app
    environment: dev # ← Composition usa isso para escolher secret aws-dev
    cost-center: CC-DEVELOPMENT
    team: backend-team
    owner: backend-team  # Obrigatório pela policy de governance
  annotations:
    owner-email: team@example.com  # Email detalhado em annotations
spec:
  # Storage configuration
  storageClass: standard
  
  # Access control
  publicAccess: false
  
  # Versioning
  versioning: false  # Desabilitado em dev
  
  # Lifecycle
  lifecycle:
    enabled: true
    expirationDays: 30  # Limpar arquivos antigos em dev
  
  # Encryption
  encryption:
    enabled: true
  
  # Governance (obrigatório)
  environment: dev
  costCenter: CC-DEVELOPMENT
  owner: team@example.com
  
  # Tags
  tags:
    project: my-project
    purpose: application-storage

