---
# Example: PostgreSQL Database Claim for Production
apiVersion: platform.example.com/v1alpha1
kind: Database
metadata:
  name: prod-app-database
  namespace: prod
  labels:
    app: my-app
    environment: prod
    cost-center: CC-PRODUCTION
    owner: team@example.com
    team: backend-team
spec:
  # Database configuration
  engine: postgresql
  engineVersion: "15"
  size: large  # Maior tamanho para produção
  storageGB: 100
  
  # Networking
  networkRef:
    id: vpc-prod-123456
    subnetIds:
    - subnet-prod-abc123
    - subnet-prod-def456
  
  # High Availability
  highAvailability: true  # Habilitado em produção
  
  # Backup
  backup:
    enabled: true
    retentionDays: 30  # Maior retenção em prod
    window: "03:00-04:00"
  
  # Security
  publiclyAccessible: false  # NUNCA true em produção
  
  # Governance (obrigatório)
  environment: prod
  costCenter: CC-PRODUCTION
  owner: team@example.com
  
  # Tags customizadas
  tags:
    project: my-project
    managed-by: platform-team
    criticality: high
    compliance: required

