---
# Example: PostgreSQL Database Claim for Homologation/Staging
apiVersion: platform.example.com/v1alpha1
kind: Database
metadata:
  name: hlm-app-database
  namespace: hlm
  labels:
    app: my-app
    environment: hlm # ← Composition usa isso para escolher secret aws-dev
    cost-center: CC-HOMOLOGATION
    team: backend-team
  annotations:
    owner: team@example.com  # Email vai em annotations, não em labels
spec:
  # Database configuration
  engine: postgresql
  engineVersion: "15"
  size: medium  # Tamanho médio para homologação
  storageGB: 50
  
  # Networking
  networkRef:
    id: vpc-hlm-123456  # Substituir pelo VPC ID real de homologação
    subnetIds:
    - subnet-hlm-abc123
    - subnet-hlm-def456
  
  # High Availability
  highAvailability: true  # Habilitado em homologação (simular prod)
  
  # Backup
  backup:
    enabled: true
    retentionDays: 14  # Retenção moderada
    window: "03:00-04:00"
  
  # Security
  publiclyAccessible: false
  
  # Governance (obrigatório)
  environment: hlm
  costCenter: CC-HOMOLOGATION
  owner: team@example.com
  
  # Tags customizadas
  tags:
    project: my-project
    managed-by: platform-team
    tier: staging

